name: vier-gewinnt site
title: null
author: Max Steidle, Lucas Krietenstein, Andreas Epp
email: Andreas.Epp@WAGO.com
remote_theme: wago-enterprise-education/wago-github-pages-theme
lang: de
plugins:
- jemoji
- jekyll-redirect-from
- jekyll-relative-links
